name: store_shot_studio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.3
  dart_mappable: ^4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  go_router: ^13.2.0
  google_fonts: ^6.2.0
  meta: ^1.11.0
  path_provider: ^2.1.2
  supabase_flutter: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  dart_mappable_builder: ^4.2.1
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/frames/phones/Apple iPhone 14/Device With Shadow/